name: _kubectl-apply

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      resource-group:
        required: true
        type: string
      cluster-name:
        required: true
        type: string
      cluster-namespace:
        required: true
        type: string
      overlays:
        required: true
        type: string
      git-sha:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      hostname:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true

jobs:
  kubectl-apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v3

    - name: 'Login - Azure'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - id: kubelogin
      name: 'Login - Kubernetes'
      uses: ./.github/actions/kubelogin
      with:
        cluster-name: ${{ inputs.cluster-name }}
        cluster-namespace: ${{ inputs.cluster-namespace }}
        resource-group: ${{ inputs.resource-group }}

    - name: 'kubectl apply (DEV or STAGING)'
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
      env:
        KUBECONFIG: ${{ github.workspace }}/${{ steps.kubelogin.outputs.kubeconfig }}
        APP_BUILD_SHA: ${{ inputs.git-sha }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        INGRESS_HOSTNAME: ${{ inputs.hostname }}
      run: |
        kubectl version --client -o yaml
        kustomize build ${{ inputs.overlays }} | envsubst
        kustomize build ${{ inputs.overlays }} | envsubst | kubectl apply -f -

    - uses: ./.github/actions/kubelogout
      name: 'Logout - Kubernetes'
      with:
        kubeconfig: ${{ steps.kubelogin.outputs.kubeconfig }}
